---
title: "HW5 EDA"
author: "Randall Thompson"
date: "5/17/2021"
output: html_document
---

```{r}
library(tidyverse)
library(GGally)
library(sf)
library(tmap)
```

```{r}
geocrime <- st_read("https://raw.githubusercontent.com/completegraph/DATA622_MACHINELEARNING/main/FINAL_PROJ/work/crimesdiv.geojson")

geodiv <- st_read("https://raw.githubusercontent.com/completegraph/DATA622_MACHINELEARNING/main/FINAL_PROJ/work/div.geojson")
```

## Demographics
```{r}
head(geodiv)
```


```{r}
skimr::skim(geodiv)
```


```{r}
sum(geodiv$approvedlots)
```


```{r}
plot(geodiv["approvedlots"])
```


```{r}
geodiv2 <- geodiv %>% 
  mutate(avg_lot_area = shape_starea/approvedlots) 
plot(geodiv["avg_lot_area"])
```


```{r}
hist(geodiv$avg_income)
```


```{r}
plot(geodiv["avg_income"])
```


```{r}
geodiv2 <- geodiv2 %>%
  mutate(income_to_lot_area = avg_income/avg_lot_area)
plot(geodiv["income_to_lot_area"])
```

## Crime

```{r}
head(geocrime)
```


```{r}
skimr::skim(geocrime)
```


```{r}
plot(geocrime["district"])
```


```{r}
data.frame(table(geocrime$crime_type, geocrime$district)) %>% 
  spread(Var2, Freq) %>% 
  mutate(total = D1+D2+D3) %>% 
  arrange(desc(total))
```


```{r}
data.frame(table(geocrime$crime_category, geocrime$district)) %>% 
  spread(Var2, Freq) %>% 
  mutate(total = D1+D2+D3) %>% 
  arrange(desc(total))
```


```{r}
data.frame(table(geocrime$offensecategory, geocrime$district)) %>% 
  spread(Var2, Freq) %>% 
  mutate(total = D1+D2+D3) %>% 
  arrange(desc(total))
```


```{r}
crime_count <- geocrime %>% 
  group_by(div_id) %>% 
  summarize(num = n()) 
geocount <- st_join(geodiv, crime_count, by = "div_id")
plot(geocount["num"])
```


```{r}
geocrime %>% 
  mutate(month = lubridate::month(newdate)) %>% 
  group_by(month) %>% 
  count(crime_category) %>% 
  ggplot(aes(month, n)) +
  geom_line() +
  facet_wrap(vars(crime_category))
```


```{r}
geocrime %>% 
  mutate(day = weekdays(newdate)) %>% 
  group_by(day) %>% 
  count(crime_category) %>% 
  ggplot(aes(day, n)) +
  geom_col() +
  facet_wrap(vars(crime_category))
```


```{r}
geocrime %>% 
  mutate(month = lubridate::month(newdate), 
         year = lubridate::year(newdate)) %>% 
  mutate(month_year = as.factor((year*100)+month)) %>% 
  group_by(month_year) %>% 
  count(crime_category) %>% 
  ggplot(aes(month_year, n)) +
  geom_col() +
  scale_x_discrete()+
  facet_wrap(vars(crime_category))
```


```{r}
crime_count2 <- geocrime %>% 
  group_by(div_id, crime_category) %>% 
  summarize(num = n()) %>% 
  spread(crime_category, num)
geocount2 <- st_join(geodiv, crime_count2, by = "div_id")
plot(geocount2[10:18])
```


